use etlcl;

select * from Healthcare;

-- 1. Retrieve the names of all patients in the database. 
select Name from Healthcare;

-- 2. List the unique medical conditions present in the dataset. 
select Medical_Condition from Healthcare;

-- 3. Find the total number of doctors in the healthcare system.
select count(Doctor) from Healthcare;

-- 4. Retrieve the details of all female patients. 
select * from Healthcare
where Gender='Female';

-- 5. what is the average age of patients in the database.
select avg(Age) from Healthcare;

-- 6. Identify the patients who have more than one medical condition. 
SELECT Name
FROM Healthcare
Group by Name
having count(Medical_condition) >1;

-- 7. List the names of all doctors.
select doctor from Healthcare;

-- 8.Identify the most common medical condition among patients.

select Medical_Condition ,count(Medical_Condition) from Healthcare
group by Medical_Condition 
order by count(Medical_Condition) desc limit 1;


-- 9.Find the patients who are older than 60 years and have diabetes. 
select Name from Healthcare
where Age>60 and Medical_Condition='diabetes';

-- 10.Calculate the total revenue generated by the healthcare system.
select sum(Billing_Amount) from Healthcare;

-- 11.11.Find the doctor with the oldest patient.
select Doctor,Name from Healthcare
order by Age desc limit 1;

-- 12.Calculate the average duration of medical visits.
select avg(duration) from Healthcare;

-- 13.Give the names of patients whose name starts with A.
select Name from Healthcare
where Name like 'a%';

-- 14.How many male and female patients are there in dataset.
select Gender,count(Gender) from Healthcare
group by Gender;

-- 15.how many patients are normal.
select Test_Results,count(Test_Results) from Healthcare
where Test_Results='Normal';

-- 16.how many patients are abnormal or Inconclusive.
select Test_Results,count(Test_Results) from Healthcare
group by Test_Results;

-- 17.how many patients of blood group AB+ are there of age above 52. 
select Blood_Type,count(Blood_Type) from Healthcare
where Age>52 and Blood_Type='AB+';

-- 18. how many patients have paid the bill above 24890. 
select  count(*) from Healthcare
where Billing_Amount>24890;

-- 19. what are the names of patients having Asthma. 
select Name from Healthcare
where Medical_Condition ='Asthma';

-- 20. how many patients have cancer.
select Medical_Condition, count(Medical_Condition) from Healthcare
where Medical_Condition='Cancer';

-- 21. what are the names and blood groups of patients admitted to room no. 292.
select Name ,Blood_Type from Healthcare
where Room_Number=292;

-- 22. how many males have Arthritis
select Medical_Condition,count(Medical_Condition) from Healthcare
where Medical_Condition='Arthritis';

-- 23. How many patients were admitted to Harris and Sons hospital.
select Hospital,count(Hospital) from Healthcare
where Hospital='Harris and Sons';

-- 24. what are the names of patients whose Insurance Provider are Cigna. 
select Name from Healthcare
where Insurance_Provider='Cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select Medical_Condition from Healthcare
where Age > (select avg(Age) from Healthcare);

